parameters:
    dnd_file_upload.twig.css_class:     'dnd-file-upload-div'
    dnd_file_upload.upload_directory:   'web/uploads'
    dnd_file_upload.allowed_mimetypes:  '*'
    dnd_file_upload.persist_entity:     false

services:
    dnd_file_upload.file_upload_extension:
        class: tps\DndFileUploadBundle\Twig\FileUploadExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }